apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gvirtus-backend
  namespace: gvirtus-system
  labels:
    app.kubernetes.io/name: gvirtus-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: gvirtus
    app.kubernetes.io/version: "0.1.0-alpha"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gvirtus-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gvirtus-backend
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: gvirtus
        app.kubernetes.io/version: "0.1.0-alpha"
    spec:
      nodeSelector:
        nvidia.com/gpu.present: "true"
      runtimeClassName: nvidia
      containers:
      - name: gvirtus-backend-containers
        image: tinghui8576/gvirtus_backend_run:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 2222
        volumeMounts:
        - name: logs
          mountPath: /home/gvirtus/logs
        - name: build
          mountPath: /gvirtus/build
      volumes:
      - name: logs
        emptyDir: {}
      - name: build
        emptyDir: {}
      restartPolicy: Always
